update of my email address and fix for AttributeError: 'Adjustment' object has no attribute 'set_all' in custom grid, behavior is still broken, but at least it runs...